import Course from '../models/Course.js';
import User from '../models/User.js';
import Quiz from '../models/Quiz.js';
import Assignment from '../models/Assignment.js';
import { getCourseThumbnail, isAutoGeneratedThumbnail } from '../utils/thumbnailGenerator.js';

const normalizeLevel = (level) => {
  const value = String(level || 'Beginner').toLowerCase();
  if (value === 'intermediate') return 'Intermediate';
  if (value === 'advanced') return 'Advanced';
  return 'Beginner';
};

const publishFields = (body) => {
  if (body.status) {
    return { status: body.status, isPublished: body.status === 'published' };
  }
  if (body.isPublished !== undefined) {
    return { isPublished: !!body.isPublished, status: body.isPublished ? 'published' : 'draft' };
  }
  return { isPublished: true, status: 'published' };
};

const canOwnCourse = (course, user) => user?.role === 'admin' || course?.instructor?.toString() === user?.id;

const findOwnedCourse = async (courseId, user, res) => {
  const course = await Course.findById(courseId);
  if (!course) {
    res.status(404).json({ success: false, message: 'Course not found' });
    return null;
  }
  if (!canOwnCourse(course, user)) {
    res.status(403).json({ success: false, message: 'Not authorized' });
    return null;
  }
  return course;
};

export const getAllCourses = async (req, res) => {
  try {
    const { category, search } = req.query;
    const filters = [{ isPublished: true }];
    if (category) filters.push({ category });
    if (search) {
      filters.push({
        $or: [
          { title: { $regex: search, $options: 'i' } },
          { description: { $regex: search, $options: 'i' } },
        ],
      });
    }

    const courses = await Course.find(filters.length > 1 ? { $and: filters } : filters[0])
      .sort({ createdAt: -1 })
      .populate('instructor', 'name email profileImage');

    res.status(200).json({ success: true, data: courses });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message || 'Server error' });
  }
};

export const getInstructorCourses = async (req, res) => {
  try {
    const query = req.user.role === 'admin' ? {} : { instructor: req.user.id };
    const courses = await Course.find(query).sort({ createdAt: -1 }).populate('instructor', 'name email profileImage');
    res.status(200).json({ success: true, data: courses });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message || 'Server error' });
  }
};

export const getCourseById = async (req, res) => {
  try {
    const course = await Course.findById(req.params.id).populate('instructor', 'name email profileImage');
    if (!course) return res.status(404).json({ success: false, message: 'Course not found' });

    const isOwner = canOwnCourse(course, req.user);
    if (!isOwner && !course.isPublished) {
      return res.status(403).json({ success: false, message: 'Course is not published' });
    }

    if (!isOwner) {
      // For students: return only preview lessons when they are NOT enrolled.
      // When enrolled, return the full lessons array.
      const { default: Enrollment } = await import('../models/Enrollment.js');
      const isEnrolled = req.user
        ? await Enrollment.findOne({
            student: req.user.id,
            course: course._id,
          })
        : null;

      const data = course.toObject();
      if (!isEnrolled) {
        data.lessons = (data.lessons || []).filter((lesson) => lesson.isFreePreview);
      }

      return res.status(200).json({ success: true, data });
    }

    res.status(200).json({ success: true, data: course });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message || 'Server error' });
  }
};

export const createCourse = async (req, res) => {
  try {
    const { title, description, category, price, thumbnail, duration, lessons } = req.body;
    if (!title || !description || !category) {
      return res.status(400).json({ success: false, message: 'Please provide title, description, and category' });
    }

    const level = normalizeLevel(req.body.level);
    
    // Use auto-generated thumbnail if no custom thumbnail provided
    const finalThumbnail = getCourseThumbnail(thumbnail, category, level);

    const course = await Course.create({
      title,
      description,
      category,
      level,
      price: Number(price) || 0,
      thumbnail: finalThumbnail,
      duration: duration || '0 hours',
      lessons: Array.isArray(lessons) ? lessons : [],
      instructor: req.user.id,
      ...publishFields(req.body),
    });

    await User.findByIdAndUpdate(req.user.id, { $addToSet: { createdCourses: course._id } });
    res.status(201).json({ success: true, data: course });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message || 'Server error' });
  }
};

export const updateCourse = async (req, res) => {
  try {
    const course = await findOwnedCourse(req.params.id, req.user, res);
    if (!course) return;

    const allowed = ['title', 'description', 'category', 'price', 'thumbnail', 'duration'];
    
    // Handle thumbnail logic before updating other fields
    let thumbnailToUse = course.thumbnail;
    
    if (req.body.thumbnail !== undefined) {
      // If thumbnail is explicitly set to null or empty string, generate auto-thumbnail
      if (req.body.thumbnail === null || req.body.thumbnail === '') {
        thumbnailToUse = getCourseThumbnail(null, course.category, course.level);
      }
      // If a custom thumbnail is provided, use it
      else if (!isAutoGeneratedThumbnail(req.body.thumbnail)) {
        thumbnailToUse = req.body.thumbnail;
      }
      // If it's an auto-generated thumbnail, keep it as is
      else {
        thumbnailToUse = req.body.thumbnail;
      }
    }
    // If category or level changed but thumbnail not explicitly updated, regenerate auto-thumbnail
    else if ((req.body.category !== undefined || req.body.level !== undefined) && 
             isAutoGeneratedThumbnail(course.thumbnail)) {
      thumbnailToUse = getCourseThumbnail(null, course.category, course.level);
    }
    
    // Update allowed fields
    allowed.forEach((field) => {
      if (req.body[field] !== undefined) course[field] = req.body[field];
    });
    
    // Handle level normalization
    if (req.body.level !== undefined) course.level = normalizeLevel(req.body.level);
    
    // Apply the determined thumbnail
    course.thumbnail = thumbnailToUse;
    
    Object.assign(course, publishFields(req.body));
    course.updatedAt = new Date();

    await course.save();
    res.status(200).json({ success: true, data: course });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message || 'Server error' });
  }
};

export const deleteCourse = async (req, res) => {
  try {
    const course = await findOwnedCourse(req.params.id, req.user, res);
    if (!course) return;

    await Promise.all([
      Course.findByIdAndDelete(course._id),
      Quiz.deleteMany({ course: course._id }),
      Assignment.deleteMany({ course: course._id }),
      User.findByIdAndUpdate(course.instructor, { $pull: { createdCourses: course._id } }),
    ]);

    res.status(200).json({ success: true, message: 'Course deleted successfully' });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message || 'Server error' });
  }
};

export const getLessons = async (req, res) => {
  try {
    const courseId = req.params.id || req.params.courseId;
    console.log('getLessons called with courseId:', courseId);
    console.log('Request params:', req.params);
    
    const course = await Course.findById(courseId);
    if (!course) return res.status(404).json({ success: false, message: 'Course not found' });

    const isOwner = canOwnCourse(course, req.user);
    if (!isOwner && !course.isPublished) return res.status(403).json({ success: false, message: 'Course is not published' });

    const lessons = [...(course.lessons || [])]
      .filter((lesson) => isOwner || lesson.isFreePreview || lesson.isFree)
      .sort((a, b) => (a.order || 0) - (b.order || 0));

    res.status(200).json({ success: true, data: lessons });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message || 'Server error' });
  }
};

export const addLesson = async (req, res) => {
  try {
    const course = await findOwnedCourse(req.params.id, req.user, res);
    if (!course) return;

    const lesson = {
      title: req.body.title,
      description: req.body.description || '',
      videoUrl: req.body.videoUrl || '',
      duration: req.body.duration || '',
      order: Number(req.body.order) || course.lessons.length + 1,
      module: req.body.module || 'Module 1',
      isFreePreview: !!(req.body.isFreePreview || req.body.isFree),
    };

    if (!lesson.title) return res.status(400).json({ success: false, message: 'Lesson title is required' });

    course.lessons.push(lesson);
    course.updatedAt = new Date();
    await course.save();
    res.status(201).json({ success: true, data: course.lessons[course.lessons.length - 1] });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message || 'Server error' });
  }
};

export const updateLesson = async (req, res) => {
  try {
    const course = await findOwnedCourse(req.params.courseId, req.user, res);
    if (!course) return;

    const lesson = course.lessons.id(req.params.lessonId);
    if (!lesson) return res.status(404).json({ success: false, message: 'Lesson not found' });

    ['title', 'description', 'videoUrl', 'duration', 'module'].forEach((field) => {
      if (req.body[field] !== undefined) lesson[field] = req.body[field];
    });
    if (req.body.order !== undefined) lesson.order = Number(req.body.order);
    if (req.body.isFreePreview !== undefined || req.body.isFree !== undefined) {
      lesson.isFreePreview = !!(req.body.isFreePreview || req.body.isFree);
    }

    course.updatedAt = new Date();
    await course.save();
    res.status(200).json({ success: true, data: lesson });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message || 'Server error' });
  }
};

export const deleteLesson = async (req, res) => {
  try {
    const course = await findOwnedCourse(req.params.courseId, req.user, res);
    if (!course) return;

    const lesson = course.lessons.id(req.params.lessonId);
    if (!lesson) return res.status(404).json({ success: false, message: 'Lesson not found' });

    lesson.deleteOne();
    course.lessons.forEach((item, index) => {
      item.order = index + 1;
    });
    course.updatedAt = new Date();
    await course.save();
    res.status(200).json({ success: true, data: course.lessons });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message || 'Server error' });
  }
};

export const reorderLessons = async (req, res) => {
  try {
    const course = await findOwnedCourse(req.params.courseId, req.user, res);
    if (!course) return;

    const { orderedLessonIds } = req.body;
    if (!Array.isArray(orderedLessonIds)) {
      return res.status(400).json({ success: false, message: 'orderedLessonIds must be an array' });
    }

    orderedLessonIds.forEach((lessonId, index) => {
      const lesson = course.lessons.id(lessonId);
      if (lesson) lesson.order = index + 1;
    });
    course.updatedAt = new Date();
    await course.save();
    res.status(200).json({ success: true, data: course.lessons.sort((a, b) => (a.order || 0) - (b.order || 0)) });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message || 'Server error' });
  }
};

export const publishCourse = async (req, res) => {
  try {
    const course = await findOwnedCourse(req.params.id, req.user, res);
    if (!course) return;
    course.isPublished = true;
    course.status = 'published';
    course.updatedAt = new Date();
    await course.save();
    res.status(200).json({ success: true, data: course });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message || 'Server error' });
  }
};

export const unpublishCourse = async (req, res) => {
  try {
    const course = await findOwnedCourse(req.params.id, req.user, res);
    if (!course) return;
    course.isPublished = false;
    course.status = 'draft';
    course.updatedAt = new Date();
    await course.save();
    res.status(200).json({ success: true, data: course });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message || 'Server error' });
  }
};

export const toggleFeatured = async (req, res) => {
  try {
    const course = await Course.findById(req.params.id);
    if (!course) return res.status(404).json({ success: false, message: 'Course not found' });
    course.isFeatured = !course.isFeatured;
    await course.save();
    res.status(200).json({ success: true, data: course });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message || 'Server error' });
  }
};

export const getFeaturedCourses = async (req, res) => {
  try {
    const courses = await Course.find({ isFeatured: true, isPublished: true })
      .sort({ createdAt: -1 })
      .populate('instructor', 'name email profileImage');
    res.status(200).json({ success: true, data: courses });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message || 'Server error' });
  }
};

// Reset course thumbnail to auto-generated
export const resetCourseThumbnail = async (req, res) => {
  try {
    const course = await findOwnedCourse(req.params.id, req.user, res);
    if (!course) return;

    // Generate auto-thumbnail based on current category and level
    course.thumbnail = getCourseThumbnail(null, course.category, course.level);
    course.updatedAt = new Date();
    
    await course.save();
    res.status(200).json({ success: true, data: course });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message || 'Server error' });
  }
};
