/**
 * Migration script to update existing courses with placeholder thumbnails
 * to use the new auto-generated SVG thumbnail system
 */

import dotenv from 'dotenv';
import connectDB from '../config/database.js';
import Course from '../models/Course.js';
import { getCourseThumbnail, isAutoGeneratedThumbnail } from '../utils/thumbnailGenerator.js';

dotenv.config();

const migrateThumbnails = async () => {
  try {
    await connectDB();
    console.log('Connected to MongoDB');

    // Find all courses with placeholder, external service, or empty thumbnails
    const placeholderPatterns = [
      'via.placeholder.com',
      'placehold.co',
      'placeholder.com'
    ];

    const courses = await Course.find({
      $or: [
        ...placeholderPatterns.map(pattern => ({
          thumbnail: { $regex: pattern, $options: 'i' }
        })),
        { thumbnail: '' },
        { thumbnail: null }
      ]
    });

    console.log(`Found ${courses.length} courses with placeholder or empty thumbnails`);

    let updated = 0;
    let skipped = 0;

    for (const course of courses) {
      // Skip if already has auto-generated thumbnail
      if (isAutoGeneratedThumbnail(course.thumbnail)) {
        skipped++;
        continue;
      }

      // Generate new auto-thumbnail
      const newThumbnail = getCourseThumbnail(null, course.category, course.level);
      
      await Course.findByIdAndUpdate(course._id, {
        thumbnail: newThumbnail
      });

      updated++;
      console.log(`Updated: ${course.title} (${course.category} - ${course.level})`);
    }

    console.log(`\n✅ Migration complete!`);
    console.log(`Updated: ${updated} courses`);
    console.log(`Skipped: ${skipped} courses (already auto-generated)`);

    process.exit(0);
  } catch (error) {
    console.error('Error during migration:', error);
    process.exit(1);
  }
};

migrateThumbnails();