/**
 * Regenerate all course thumbnails with unique IDs
 */

import dotenv from 'dotenv';
import connectDB from '../config/database.js';
import Course from '../models/Course.js';
import { getCourseThumbnail, isAutoGeneratedThumbnail } from '../utils/thumbnailGenerator.js';

dotenv.config();

const regenerateAllThumbnails = async () => {
  try {
    await connectDB();
    console.log('Connected to MongoDB');

    const courses = await Course.find({});
    console.log(`Found ${courses.length} courses`);

    let updated = 0;
    let skipped = 0;

    for (const course of courses) {
      // Only regenerate auto-generated thumbnails
      if (!isAutoGeneratedThumbnail(course.thumbnail)) {
        console.log(`Skipped: ${course.title} (has custom thumbnail)`);
        skipped++;
        continue;
      }

      const newThumbnail = getCourseThumbnail(null, course.category, course.level);
      
      course.thumbnail = newThumbnail;
      await course.save();

      updated++;
      console.log(`Updated: ${course.title} (${course.category} - ${course.level})`);
    }

    console.log(`\n✅ Regeneration complete!`);
    console.log(`Updated: ${updated} courses`);
    console.log(`Skipped: ${skipped} courses (custom thumbnails)`);

    process.exit(0);
  } catch (error) {
    console.error('Error during regeneration:', error);
    process.exit(1);
  }
};

regenerateAllThumbnails();