/**
 * Test script to verify thumbnail reset functionality
 */

import dotenv from 'dotenv';
import connectDB from '../config/database.js';
import Course from '../models/Course.js';
import { getCourseThumbnail, isAutoGeneratedThumbnail } from '../utils/thumbnailGenerator.js';

dotenv.config();

const testThumbnailReset = async () => {
  try {
    await connectDB();
    console.log('Connected to MongoDB');

    // Find a course with a custom thumbnail
    const course = await Course.findOne({
      thumbnail: { $exists: true, $ne: '', $ne: null },
      $nor: [
        { thumbnail: { $regex: 'data:image/svg+xml;base64,' } }
      ]
    });

    if (!course) {
      console.log('No courses with custom thumbnails found for testing');
      process.exit(0);
    }

    console.log(`\nTesting thumbnail reset for: ${course.title}`);
    console.log(`Current thumbnail: ${course.thumbnail.substring(0, 60)}...`);
    console.log(`Category: ${course.category}, Level: ${course.level}`);

    // Simulate the reset functionality
    const oldThumbnail = course.thumbnail;
    const newThumbnail = getCourseThumbnail(null, course.category, course.level);
    
    console.log(`\nNew auto-generated thumbnail: ${newThumbnail.substring(0, 60)}...`);
    console.log(`Is auto-generated: ${isAutoGeneratedThumbnail(newThumbnail)}`);

    // Test the update (without actually saving)
    console.log(`\n✅ Thumbnail reset test successful!`);
    console.log(`The course would be updated from:`);
    console.log(`  Old: ${oldThumbnail.substring(0, 60)}...`);
    console.log(`  New: ${newThumbnail.substring(0, 60)}...`);

    process.exit(0);
  } catch (error) {
    console.error('Error during test:', error);
    process.exit(1);
  }
};

testThumbnailReset();